'use strict';

const config = {
  style: 'mapbox://styles/mapbox/light-v10',
  accessToken:
    'pk.eyJ1IjoianVuZTk5OTgiLCJhIjoiY2xnbG91MGYwMDJ5OTNmb2V6dHBsZmJtMSJ9.hehQxfYji16TNQ92jOwx4A',
  CSV: './Sample_Data.csv',
  center: [-73.935242, 40.730610],
  zoom: 6,
  title: 'Cornell Physician Directory',
  description:
    'A map directory of cornell physicians filterable and searchable by multiple variables',
  sideBarInfo: ['Name','Primary Specialty','Languages','Address','Number','WCM Find A Doctor URL'],
  popupInfo: ['Name'],
  filters: [
    {
      type: 'dropdown',
      title: 'Languages supported: ',
      columnHeader: 'Languages',
      listItems: [
        'Amharic',
        'ASL',
        'Cambodian',
        'Chinese',
        'Danish',
        'English',
        'French',
        'German',
        'Greek',
        'Hindi',
        'Italian',
        'Japanese',
        'Korean',
        'Language Line Services',
        'Norwegian',
        'Oriya',
        'Portuguese',
        'Punjabi',
        'Russian',
        'Somali',
        'Spanish',
        'Swedish',
        'Tagalog',
        'Thai',
        'Tigrinya',
        'Tongan',
        'Vietnamese',
        'Ukranian',
      ],
    },
    {
      type: 'dropdown',
      title: 'Primary Specialty: ',
      columnHeader: 'Primary Specialty',
      listItems: [
          'Acupuncture',
          'Addiction Psychiatry',  
          'Anesthesiology',  
          'Audiology',  
          'Bariatric Surgery', 
          'Cardiac Surgery',
          'Cardiology',  
          'Cardiovascular Disease',  
          'Certified Professional Midwife',  
          'Child and Adolescent Psychiatry', 
          'Child and Adolescent Psychology', 
          'Clinical Genetics',  
          'Colon and Rectal Surgery',  
          'Complex General Surgical Oncology',  
          'Critical Care Medicine', 
          'Cytopathology',  
          'Dentistry',  
          'Dermatology',  
          'Dermatopathology', 
          'Developmental-Behavioral Pediatrics',  
          'Diagnostic Radiology',  
          'Emergency Medicine',  
          'Endocrine Surgery', 
          'Endocrinology, Diabetes and Metabolism',  
          'Facial Plastic and Reconstructive Surgery',  
          'Family Medicine',  
          'Gastroenterology', 
          'Gastrointestinal Pathology',  
          'General Pediatrics',  
          'Geriatric Medicine',  
          'Gynecologic Oncology', 
          'Hematology/Oncology',  
          'Hematopathology',  
          'Hospice and Palliative Medicine',  
          'Hospital Medicine', 
          'Infectious Disease',  
          'Internal Medicine',  
          'Massage Therapy',  
          'Maternal and Fetal Medicine',
          'Medical Oncology',  
          'Minimally Invasive Gynecologic Surgery',  
          'Molecular Hematopathology', 
          'Neonatal-Perinatal Medicine',  
          'Nephrology',  
          'Neuro-Oncology',  
          'Neurological Surgery', 
          'Neurology',  
          'Neuropsychology',  
          'Neuroradiology',  
          'Nuclear Medicine', 
          'Nurse Practitioner',  
          'Nutrition',  
          'Obstetrics and Gynecology',  
          'Ophthalmology', 
          'Optometry',  
          'Oral and Maxillofacial Pathology',  
          'Oral and Maxillofacial Surgery',  
          'Orthopedic Surgery', 
          'Otolaryngology - Head & Neck Surgery',  
          'Pain Medicine/Management',  
          'Pathology',  
          'Pathology - Anatomic', 
          'Pathology - Anatomic & Clinical',  
          'Pathology - Molecular Genetic',  
          'Pediatric Allergy and Immunology',  
          'Pediatric Anesthesiology',
          'Pediatric Cardiology',  
          'Pediatric Critical Care Medicine', 
          'Pediatric Dentistry',  
          'Pediatric Dermatology',  
          'Pediatric Emergency Medicine',  
          'Pediatric Endocrinology', 
          'Pediatric Gastroenterology',  
          'Pediatric Hematology-Oncology',  
          'Pediatric Hospitalist',  
          'Pediatric Infectious Diseases', 
          'Pediatric Nephrology',  
          'Pediatric Neurological Surgery',  
          'Pediatric Neurology',  
          'Pediatric Otolaryngology', 
          'Pediatric Pulmonology',  
          'Pediatric Rheumatology',  
          'Pediatric Surgery',  
          'Pediatric Urology', 
          'Pediatric/Congenital Cardiac Surgery',  
          'Pediatrics',  
          'Physical Medicine and Rehabilitation',  
          'Plastic and Reconstructive Surgery',
          'Podiatry',  
          'Primary Specialty', 
          'Psychiatry',  
          'Psychology',  
          'Public Health-Preventative Medicine',  
          'Pulmonary Critical Care Medicine', 
          'Pulmonary Disease Medicine',  
          'Radiation Oncology',  
          'Radiology',  
          'Registered Dietitian', 
          'Reproductive Endocrinology/Infertility',  
          'Rheumatology',  
          'Sleep Medicine',  
          'Social Worker', 
          'Speech and Language Pathology',  
          'Surgery',  
          'Surgical Critical Care',  
          'Thoracic Surgery', 
          'Transplant Hepatology',  
          'Transplant Surgery',  
          'Urogynecology',  
          'Urology',
          'Vascular and Interventional Radiology',  
          'Vascular Surgery',
          ],
    },
    {
      type: 'dropdown',
      title: 'Accepted Insurance: ',
      columnHeader: 'Accepted Insurance',
      listItems: [
           
          'AETNA HMO', 
          'AETNA Medicare', 
          'AETNA PPO', 
          'Aetna - NYP EPO/POS', 
          'Aetna Weill Cornell Employee Managed Care Plan ', 
          'Aetna Weill Cornell Employee PPO Plan ', 
          'Affinity Access ', 
          'Affinity Health Plan ', 
          'AgeWell New York ', 
          'Amida Care ', 
          'CIGNA ', 
          'Emblem Select Care ', 
          'Empire Blue Cross/Blue Shield Blue Access', 
          'Empire Blue Cross/Blue Shield Blue Connection', 
          'Empire Blue Cross/Blue Shield EPO', 
          'Empire Blue Cross/Blue Shield HMO', 
          'Empire Blue Cross/Blue Shield Mediblue (Senior)', 
          'Empire Blue Cross/Blue Shield PPO', 
          'Empire Blue Cross/Blue Shield HealthPlus ', 
          'Empire Blue Cross/Blue Shield HealthPlus CHP', 
          'Fidelis Care ', 'GHI CBP', 'Health First ', 
          'Health Insurance Plan of NY (HIP) ', 
          'Health Insurance Plan of NY (HIP) Medicaid', 
          'Health Insurance Plan of NY (HIP) Medicare', 
          'Medicaid ', 'Medicare ', 
          'Oxford Health Plans Freedom', 
          'Oxford Health Plans Liberty', 
          'Oxford Health Plans Medicare Advantage', 
          'Oxford Health Plans Metro/Core/Charter', 
          'Rockefeller University - Trustmark ', 
          'United Empire ', 'United Healthcare ', 
          'United Healthcare Community Plan', 
          'United Healthcare Medicare', 
          'United Healthcare Compass ', 
          'VNSNY CHOICE HMO', 
          'VNSNY CHOICE Medicare', 
          'WellCare of NY ', 
          'WorldWide Medical ', 
          'Aetna - Weill Cornell Medicine PPO (Cornell University)'
      ],
    },
    {
        type: 'checkbox',
        title: 'Video Visits Available: ',
        columnHeader: 'Video Visits Available', // Case sensitive - must match spreadsheet entry
        listItems: [
          'Yes',
          'No',
          'N/A'], // Case sensitive - must match spreadsheet entry; This will take up to six inputs but is best used with a maximum of three;
    },
    {
        type: 'checkbox',
        title: 'Accepting New Patients: ',
        columnHeader: 'Accepting New Patients', // Case sensitive - must match spreadsheet entry
        listItems: [
          'Yes',
          'No',
        ],
    },
  ],
};